___

<a href='http://www.pieriandata.com'> <img src='../Pierian_Data_Logo.png' /></a>
___
# TensorFlow Basics

Remember to reference the video for full explanations, this is just a notebook for code reference.

You can import the library:

In [1]:
import tensorflow as tf

2025-01-24 14:07:51.938750: I tensorflow/core/util/port.cc:153] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2025-01-24 14:07:51.946873: I external/local_xla/xla/tsl/cuda/cudart_stub.cc:32] Could not find cuda drivers on your machine, GPU will not be used.
2025-01-24 14:07:51.974585: I external/local_xla/xla/tsl/cuda/cudart_stub.cc:32] Could not find cuda drivers on your machine, GPU will not be used.
2025-01-24 14:07:52.008890: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:477] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
E0000 00:00:1737724072.053060   23711 cuda_dnn.cc:8310] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
E0000 00:00:1737724072.06

In [2]:
print(tf.__version__)

2.18.0


### Simple Constants

Let's show how to create a simple constant with Tensorflow, which TF stores as a tensor object:

In [3]:
hello = tf.constant('Hello World')

2025-01-24 14:07:56.402913: E external/local_xla/xla/stream_executor/cuda/cuda_driver.cc:152] failed call to cuInit: INTERNAL: CUDA error: Failed call to cuInit: UNKNOWN ERROR (303)


In [4]:
type(hello)

tensorflow.python.framework.ops.EagerTensor

In [5]:
x = tf.constant(100)

In [6]:
type(x)

tensorflow.python.framework.ops.EagerTensor

### Running Sessions

Now you can create a TensorFlow Session, which is a class for running TensorFlow operations.

A `Session` object encapsulates the environment in which `Operation`
objects are executed, and `Tensor` objects are evaluated. For example:

In [7]:
sess = tf.Session()

AttributeError: module 'tensorflow' has no attribute 'Session'

In [ ]:
sess.run(hello)

In [ ]:
type(sess.run(hello))

In [ ]:
sess.run(x)

In [ ]:
type(sess.run(x))

## Operations

You can line up multiple Tensorflow operations in to be run during a session:

In [8]:
x = tf.constant(2)
y = tf.constant(3)

In [9]:
with tf.Session() as sess:
    print('Operations with Constants')
    print('Addition',sess.run(x+y))
    print('Subtraction',sess.run(x-y))
    print('Multiplication',sess.run(x*y))
    print('Division',sess.run(x/y))

AttributeError: module 'tensorflow' has no attribute 'Session'

### Placeholder

You may not always have the constants right away, and you may be waiting for a constant to appear after a cycle of operations. **tf.placeholder** is a tool for this. It inserts a placeholder for a tensor that will be always fed.

**Important**: This tensor will produce an error if evaluated. Its value must be fed using the `feed_dict` optional argument to `Session.run()`,
`Tensor.eval()`, or `Operation.run()`. For example, for a placeholder of a matrix of floating point numbers:

    x = tf.placeholder(tf.float32, shape=(1024, 1024))

Here is an example for integer placeholders:

In [10]:
x = tf.placeholder(tf.int32)
y = tf.placeholder(tf.int32)

AttributeError: module 'tensorflow' has no attribute 'placeholder'

In [11]:
x

<tf.Tensor: shape=(), dtype=int32, numpy=2>

In [12]:
type(x)

tensorflow.python.framework.ops.EagerTensor

### Defining Operations

In [13]:
add = tf.add(x,y)
sub = tf.subtract(x,y)
mul = tf.multiply(x,y)

Running operations with variable input:

In [14]:
d = {x:20,y:30}

TypeError: Tensor is unhashable. Instead, use tensor.ref() as the key.

In [ ]:
with tf.Session() as sess:
    print('Operations with Constants')
    print('Addition',sess.run(add,feed_dict=d))
    print('Subtraction',sess.run(sub,feed_dict=d))
    print('Multiplication',sess.run(mul,feed_dict=d))

Now let's see an example of a more complex operation, using Matrix Multiplication. First we need to create the matrices:

In [15]:
import numpy as np
# Make sure to use floats here, int64 will cause an error.
a = np.array([[5.0,5.0]])
b = np.array([[2.0],[2.0]])

In [16]:
a

array([[5., 5.]])

In [17]:
a.shape

(1, 2)

In [18]:
b

array([[2.],
       [2.]])

In [ ]:
b.shape

In [ ]:
mat1 = tf.constant(a)

In [ ]:
mat2 = tf.constant(b)

The matrix multiplication operation:

In [ ]:
matrix_multi = tf.matmul(mat1,mat2)

Now run the session to perform the Operation:

In [ ]:
with tf.Session() as sess:
    result = sess.run(matrix_multi)
    print(result)

That is all for now! Next we will expand these basic concepts to construct out own Multi-Layer Perceptron model!

# Great Job!